name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Show info
        run: cat $GITHUB_EVENT_PATH
      - name: Show info
        env:
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: echo "${EVENT_PAYLOAD}" | jq .
