name: Publish Packages
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  publish_packages:
    name: Publish Packages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show info
        run: cat $GITHUB_EVENT_PATH
      # - name: Setup
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 8
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: pnpm install
      # - name: Build
      #   run: pnpm build
      # - name: Release packages
      #   run: pnpm publish --recursive --tag ${{ inputs.tag }} --filter "@tutorialkit/*" --filter tutorialkit --filter create-tutorial
      # - name: Run integration tests
      #   run: pnpm --filter tutorialkit-integration run test
